server:
  port: 2224
spring:
  application:
    name: robbn-server
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springboot?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5555/eureka/
    healthcheck:
      enabled: true
  instance:
    status-page-url: http://localhost:${server.port}/swagger-ui.html
mybatis:
  mapper-locations: classpath:mapper/*.xml
  #type-aliases-package: com.chaoqi.springboot_mybatisplus.domain